version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: postgres-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile
      target: ${TARGET:-production}
    ports:
      - "5000:5000"
    volumes:
      - ../backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=${TARGET:-production}
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
    profiles:
      - ${TARGET:-production}

  frontend:
    build:
      context: ..
      dockerfile: docker/client.Dockerfile
      target: ${TARGET:-production}
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=${TARGET:-production}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://backend:5000/api}
    depends_on:
      - backend
    profiles:
      - ${TARGET:-production}

volumes:
  postgres_data:
